// Project Makoto
// Copyright (C) 2023  Fortunevale
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY
namespace ProjectMakoto.Plugins.Music.Entities;
#pragma warning disable CS8981
#pragma warning disable CS8618
#pragma warning disable IDE1006
public class Translations : ITranslations
{
    public Dictionary<string, int> Progress = new();
    public CommandTranslation[] CommandList { get; set; }
    #region AutoGenerated
    public commands Commands;
    public sealed class commands
    {
        public music Music;
        public sealed class music
        {
            public playlists Playlists;
            public sealed class playlists
            {
                public modify Modify;
                public sealed class modify
                {
                    public SingleTranslationKey DeleteNote;
                    public SingleTranslationKey HexHelp;
                    public SingleTranslationKey NewPlaylistColorPrompt;
                    public SingleTranslationKey NewPlaylistColor;
                    public SingleTranslationKey ThumbnailError;
                    public SingleTranslationKey ThumbnailSizeError;
                    public SingleTranslationKey ImportingThumbnail;
                    public SingleTranslationKey UploadThumbnail;
                    public SingleTranslationKey AddSong;
                    public SingleTranslationKey TrackLimit;
                    public SingleTranslationKey ModifyingPlaylist;
                    public SingleTranslationKey Track;
                    public SingleTranslationKey CurrentTrackCount;
                    public SingleTranslationKey RemoveDuplicates;
                    public SingleTranslationKey RemoveTracks;
                    public SingleTranslationKey AddTracks;
                    public SingleTranslationKey ChangeThumbnail;
                    public SingleTranslationKey ChangeColor;
                    public SingleTranslationKey ChangeName;
                }
                public createPlaylist CreatePlaylist;
                public sealed class createPlaylist
                {
                    public SingleTranslationKey Created;
                    public SingleTranslationKey Creating;
                    public SingleTranslationKey SupportedAddType;
                    public SingleTranslationKey SetFirstTracks;
                    public SingleTranslationKey SetPlaylistName;
                    public SingleTranslationKey FirstTracks;
                    public SingleTranslationKey PlaylistName;
                    public SingleTranslationKey CreatePlaylist;
                    public SingleTranslationKey ChangeTracks;
                    public SingleTranslationKey ChangeName;
                }
                public import Import;
                public sealed class import
                {
                    public SingleTranslationKey ImportFailed;
                    public SingleTranslationKey Importing;
                    public SingleTranslationKey UploadExport;
                    public SingleTranslationKey Created;
                    public SingleTranslationKey Creating;
                    public SingleTranslationKey NotLoaded;
                    public SingleTranslationKey PlaylistUrl;
                    public SingleTranslationKey ImportPlaylist;
                    public SingleTranslationKey ImportMethod;
                    public SingleTranslationKey ExportedPlaylist;
                    public SingleTranslationKey Link;
                }
                public delete Delete;
                public sealed class delete
                {
                    public SingleTranslationKey Deleted;
                    public SingleTranslationKey Deleting;
                }
                public export Export;
                public sealed class export
                {
                    public SingleTranslationKey Exported;
                }
                public share Share;
                public sealed class share
                {
                    public MultiTranslationKey Shared;
                }
                public addToQueue AddToQueue;
                public sealed class addToQueue
                {
                    public SingleTranslationKey Adding;
                }
                public manage Manage;
                public sealed class manage
                {
                    public SingleTranslationKey PlaylistSelectorDelete;
                    public SingleTranslationKey PlaylistSelectorModify;
                    public SingleTranslationKey PlaylistSelectorExport;
                    public SingleTranslationKey PlaylistSelectorShare;
                    public SingleTranslationKey PlaylistSelectorQueue;
                    public SingleTranslationKey DeleteButton;
                    public SingleTranslationKey ModifyButton;
                    public SingleTranslationKey CreateNewButton;
                    public SingleTranslationKey SaveCurrentButton;
                    public SingleTranslationKey ImportButton;
                    public SingleTranslationKey ExportButton;
                    public SingleTranslationKey ShareButton;
                    public SingleTranslationKey AddToQueueButton;
                    public SingleTranslationKey NoPlaylists;
                }
                public loadShare LoadShare;
                public sealed class loadShare
                {
                    public SingleTranslationKey Imported;
                    public SingleTranslationKey Importing;
                    public SingleTranslationKey ImportButton;
                    public SingleTranslationKey CreatedBy;
                    public SingleTranslationKey PlaylistName;
                    public SingleTranslationKey Found;
                    public SingleTranslationKey NotFound;
                    public SingleTranslationKey Loading;
                }
                public SingleTranslationKey ThumbnailModerationNote;
                public SingleTranslationKey NameModerationNote;
                public SingleTranslationKey Tracks;
                public SingleTranslationKey NoPlaylist;
                public SingleTranslationKey PlayListLimit;
                public SingleTranslationKey Title;
            }
            public skip Skip;
            public sealed class skip
            {
                public SingleTranslationKey VoteButton;
                public SingleTranslationKey VoteStarted;
                public SingleTranslationKey Skipped;
                public SingleTranslationKey AlreadyVoted;
            }
            public shuffle Shuffle;
            public sealed class shuffle
            {
                public SingleTranslationKey Off;
                public SingleTranslationKey On;
            }
            public repeat Repeat;
            public sealed class repeat
            {
                public SingleTranslationKey Off;
                public SingleTranslationKey On;
            }
            public removeQueue RemoveQueue;
            public sealed class removeQueue
            {
                public SingleTranslationKey Removed;
                public SingleTranslationKey NoSong;
                public SingleTranslationKey OutOfRange;
            }
            public join Join;
            public sealed class join
            {
                public SingleTranslationKey AlreadyUsed;
                public SingleTranslationKey Joined;
            }
            public queue Queue;
            public sealed class queue
            {
                public SingleTranslationKey Play;
                public SingleTranslationKey Repeat;
                public SingleTranslationKey Shuffle;
                public SingleTranslationKey NoSong;
                public SingleTranslationKey CurrentlyPlaying;
                public SingleTranslationKey Track;
                public SingleTranslationKey QueueCount;
            }
            public play Play;
            public sealed class play
            {
                public SingleTranslationKey SearchSuccess;
                public SingleTranslationKey NoMatches;
                public SingleTranslationKey FailedToLoad;
                public SingleTranslationKey PlatformSelect;
                public SingleTranslationKey LookingForPlatform;
                public SingleTranslationKey LookingFor;
                public SingleTranslationKey Duration;
                public SingleTranslationKey Uploader;
                public SingleTranslationKey QueuePosition;
                public SingleTranslationKey QueuePositions;
                public SingleTranslationKey QueuedSingle;
                public SingleTranslationKey QueuedMultiple;
                public SingleTranslationKey Preparing;
            }
            public pause Pause;
            public sealed class pause
            {
                public SingleTranslationKey Resumed;
                public SingleTranslationKey Paused;
            }
            public forceSkip ForceSkip;
            public sealed class forceSkip
            {
                public SingleTranslationKey Skipped;
            }
            public forceDisconnect ForceDisconnect;
            public sealed class forceDisconnect
            {
                public SingleTranslationKey Disconnected;
            }
            public forceClearQueue ForceClearQueue;
            public sealed class forceClearQueue
            {
                public SingleTranslationKey Cleared;
            }
            public disconnect Disconnect;
            public sealed class disconnect
            {
                public SingleTranslationKey VoteButton;
                public SingleTranslationKey VoteStarted;
                public SingleTranslationKey Disconnected;
                public SingleTranslationKey AlreadyVoted;
            }
            public clearQueue ClearQueue;
            public sealed class clearQueue
            {
                public SingleTranslationKey VoteButton;
                public SingleTranslationKey VoteStarted;
                public SingleTranslationKey Cleared;
                public SingleTranslationKey AlreadyVoted;
            }
            public SingleTranslationKey DjRole;
            public SingleTranslationKey NotSameChannel;
        }
    }
    #endregion AutoGenerated
}